version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@2.0.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  api:
    executor: node/default
    steps:
      - checkout:
          path: ./
      - run:
          name: install api dependencies
          command: npm run api:install
      - run:
          name: building and deploying the api
          command: npm run api:deploy

  frontend:
    executor: node/default
    steps:
      - checkout:
          path: ./
      - run:
          name: install frontend dependencies
          command: npm run frontend:install
      - aws-cli/install
      - run:
          name: building and deploying the frontend
          command: npm run frontend:deploy

workflows:
  udagram:
    jobs:
      - frontend
      - api